version: '3.8'

services:
  db:
    image: postgres:15
    container_name: uptime_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data


  bot:
    build:
      context: .
    command: python -m bot.main
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app

volumes:
  pg_data: